<#
.SYNOPSIS
    Build the MSI installer for mRemoteNG.
.DESCRIPTION
    Generates a WiX file list from the build output, then builds
    the WiX 7 SDK project to produce the MSI installer.
.PARAMETER NoBuild
    Skip building the main application (use existing build output).
.PARAMETER HarvestPath
    Override the path to harvest files from.
#>
param(
    [switch]$NoBuild,
    [string]$HarvestPath
)

$ErrorActionPreference = "Stop"
$repoRoot = $PSScriptRoot

# --- Extract version from csproj ---
$csproj = Get-Content "$repoRoot\mRemoteNG\mRemoteNG.csproj" -Raw
if ($csproj -match '<Version>([^<]+)</Version>') {
    $fullVersion = $matches[1].Trim()
    # MSI version: strip prerelease suffix (MSI only supports a.b.c.d numeric)
    if ($fullVersion -match '^(\d+\.\d+\.\d+)') {
        $msiVersion = $matches[1]
    } else {
        throw "Could not parse numeric version from: $fullVersion"
    }
} else {
    throw "Could not find <Version> in mRemoteNG.csproj"
}
Write-Host "Product version: $fullVersion (MSI: $msiVersion)" -ForegroundColor Cyan

# --- Build main application if needed ---
if (-not $NoBuild) {
    Write-Host "`n=== Building mRemoteNG ===" -ForegroundColor Cyan
    & pwsh -NoProfile -ExecutionPolicy Bypass -File "$repoRoot\build.ps1"
    if ($LASTEXITCODE -ne 0) { throw "Build failed with exit code $LASTEXITCODE" }
}

# --- Determine harvest path ---
if (-not $HarvestPath) {
    $HarvestPath = "$repoRoot\mRemoteNG\bin\x64\Release"
}
if (-not (Test-Path $HarvestPath)) {
    throw "Harvest path not found: $HarvestPath"
}
$HarvestPath = (Resolve-Path $HarvestPath).Path
Write-Host "Harvest path: $HarvestPath"

# --- Generate WiX file list ---
Write-Host "`n=== Generating file list ===" -ForegroundColor Cyan

$excludeDirs = @('ref', 'publish', 'win-x64', 'win-x86', 'win-arm64', 'win-x64-sc')
$excludeExts = @('.pdb', '.log')
$sourceLen = $HarvestPath.TrimEnd('\').Length + 1

# Collect all files with their relative paths
$allFiles = Get-ChildItem -Path $HarvestPath -Recurse -File | Where-Object {
    $rel = $_.FullName.Substring($sourceLen)
    $parts = $rel -split '\\'
    $topDir = if ($parts.Count -gt 1) { $parts[0] } else { $null }
    ($null -eq $topDir -or $topDir -notin $excludeDirs) -and
    $_.Extension -notin $excludeExts
}

# Collect unique directory paths and assign WiX IDs
$dirMap = @{}  # relative path -> WiX Directory Id
$dirMap[''] = 'INSTALLFOLDER'

foreach ($file in $allFiles) {
    $rel = $file.FullName.Substring($sourceLen)
    $dir = [System.IO.Path]::GetDirectoryName($rel)
    # Add all ancestor directories (ensures intermediate dirs exist in tree)
    $current = $dir
    while ($current -and -not $dirMap.ContainsKey($current)) {
        $wixId = 'dir_' + ($current -replace '[^A-Za-z0-9_.]', '_')
        $dirMap[$current] = $wixId
        $current = [System.IO.Path]::GetDirectoryName($current)
    }
}

# Build directory tree structure
function Build-DirectoryXml {
    param(
        [string]$ParentPath,
        [int]$Indent
    )
    $prefix = '  ' * $Indent
    $children = $dirMap.Keys | Where-Object {
        $_ -ne '' -and
        [System.IO.Path]::GetDirectoryName($_) -eq $ParentPath
    } | Sort-Object

    foreach ($child in $children) {
        $name = [System.IO.Path]::GetFileName($child)
        $id = $dirMap[$child]
        $script:wxsContent += "$prefix<Directory Id=`"$id`" Name=`"$name`">`n"
        Build-DirectoryXml -ParentPath $child -Indent ($Indent + 1)
        $script:wxsContent += "$prefix</Directory>`n"
    }
}

# Generate the WiX XML
$script:wxsContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by build-msi.ps1. Do not edit manually. -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <DirectoryRef Id="INSTALLFOLDER">

"@

Build-DirectoryXml -ParentPath '' -Indent 3

$script:wxsContent += @"
    </DirectoryRef>
  </Fragment>

  <Fragment>
    <ComponentGroup Id="AppFiles">

"@

# Add components for each file
$compCounter = 0
foreach ($file in ($allFiles | Sort-Object FullName)) {
    $rel = $file.FullName.Substring($sourceLen)
    $dir = [System.IO.Path]::GetDirectoryName($rel)
    $dirId = if ($dir) { $dirMap[$dir] } else { 'INSTALLFOLDER' }
    $compCounter++

    $escapedSource = "`$(var.HarvestPath)\$rel" -replace '&', '&amp;'
    $script:wxsContent += @"
      <Component Id="comp_$compCounter" Directory="$dirId">
        <File Source="$escapedSource" />
      </Component>

"@
}

$script:wxsContent += @"
    </ComponentGroup>
  </Fragment>
</Wix>
"@

$generatedFile = "$repoRoot\mRemoteNGInstaller\_GeneratedFiles.wxs"
$script:wxsContent | Out-File -FilePath $generatedFile -Encoding UTF8
$fileCount = $compCounter
$dirCount = $dirMap.Count - 1  # exclude root
Write-Host "Generated: $generatedFile ($fileCount files, $dirCount directories)"

# --- Build MSI ---
Write-Host "`n=== Building MSI Installer ===" -ForegroundColor Cyan
$wixProj = "$repoRoot\mRemoteNGInstaller\mRemoteNGInstaller.wixproj"

dotnet build $wixProj `
    -c Release `
    "-p:InstallerPlatform=x64" `
    "-p:HarvestPath=$HarvestPath" `
    "-p:ProductVersion=$msiVersion" `
    "-p:SolutionDir=$repoRoot\"

if ($LASTEXITCODE -ne 0) { throw "MSI build failed with exit code $LASTEXITCODE" }

# --- Report ---
$msiSearchPaths = @(
    "$repoRoot\mRemoteNGInstaller\bin\x64\Release\en-US",
    "$repoRoot\mRemoteNGInstaller\bin\x64\Release",
    "$repoRoot\mRemoteNGInstaller\bin\Release"
)
$msi = $null
foreach ($searchPath in $msiSearchPaths) {
    $msi = Get-ChildItem -Path $searchPath -Filter "*.msi" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($msi) { break }
}

if ($msi) {
    $sizeMB = [math]::Round($msi.Length / 1MB, 1)
    Write-Host "`n=== MSI Created ===" -ForegroundColor Green
    Write-Host "Output saved to: $($msi.FullName) ($sizeMB MB)"
} else {
    Write-Host "`nMSI file location:" -ForegroundColor Yellow
    Get-ChildItem -Path "$repoRoot\mRemoteNGInstaller\bin" -Recurse -Filter "*.msi" -ErrorAction SilentlyContinue | ForEach-Object {
        Write-Host "  $($_.FullName) ($([math]::Round($_.Length / 1MB, 1)) MB)"
    }
}
