sonar.projectKey=robertpopa22_mRemoteNG
sonar.organization=robertpopa22
sonar.sources=mRemoteNG/
sonar.tests=mRemoteNGTests/,mRemoteNGSpecs/
sonar.sourceEncoding=UTF-8
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/obj/**,**/bin/**,**/*.Designer.cs,**/Interop*.cs
